### ISSUE TITLE
Device Details - Show Errors and Warnings alerts

### ISSUE THREAD

**Issue by mikewuu** [seamapi/react#109]
Should show an alert when device is in privacy mode to indicate that access codes won't work:

![Image](https://user-images.githubusercontent.com/11449462/236984903-a6b9a508-d97a-4f53-b4dd-bdb02d5dce67.png)

[Figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Prebuilt-Components?type=design&node-id=291-40595&t=dKwaWxwLBxFyHpV7-0)

**Comment by mikewuu** [comment]
@miken-seam @dawnho  what would clicking **View setting** do?

**Comment by dawnho** [comment]
@mikewuu let's leave out the "View setting" button.

The warnings and errors should be populated in the device object.
It's usually laid out in an array, we can just list them out.

The warnings will be orange, errors will be red.

See our docs to see what the `errors` and `warnings` payloads look like:
https://docs.seam.co/latest/api-clients/devices#device-error-types

See this metabase table to see some example of the data:
https://seam.metabaseapp.com/question/78-devices-error-and-warning-map
