### ISSUE TITLE
Device Details - Add properties (ability to show device properties)

### ISSUE THREAD

**Issue by mikewuu** [seamapi/react#111]
Device detail's has several controls that the user can edit:

![Image](https://user-images.githubusercontent.com/11449462/236985701-6bb6a56d-7a25-426c-9ebf-644aed4212e3.png)

[figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Prebuilt-Components?type=design&node-id=322-38129&t=dKwaWxwLBxFyHpV7-0)

### Controls

- [ ] Edit code
- [ ] Edit code length
- [ ] One touch lock toggle on/off
- [ ] Edit noise level

**Comment by mikewuu** [comment]
@miken-seam I can't seem to find the design for what happens when the user clicks **Edit**.

**Comment by dawnho** [comment]
@mikewuu for the props / actiosn:

For door locks, we should only have:
- Lock / Unlock action
- Display Code Length, do not allow edit

For noise sensors, we can:
- Show Noise level

**Comment by mikewuu** [comment]
Doesn't look like there are any other properties required controls for now as we're only handling locks. 

@dawnho , going to close this issue, and open new ones as we identify missing controls / properties.
