### ISSUE TITLE
Get default user session key from API

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#13]
Will API generate one for us and return it? If so we can remove the uuid package and logic.

**Comment by seveibar** [comment]
I think conceptually we should never generate "unique group keys" for customers- but then again I'm making an exception by saying the browser fingerprint version is ok. I think it's better to break the rule on an opinionated client than on the "more long term, more important" server.

I am not opposed to the backend `POST /client_sessions/create` not requiring a `userIdentifierKey`, but in that case I would think that the token could be stored and passed around and the `user_identifier_key` is null. I also think that it's a fairly small phase where `userIdentifierKey` is used, and it's cleaner to just have a really descriptive browser fingerprint as the key as customers transition out of the auto-generated user identifier key phase.

CC @azat-co

**Comment by seveibar** [comment]
Minor correction: `user_identifier_key` should be optional on backend, because for some backend implementations customers will choose to manage their users without any `user_identifier_keys` by storing the tokens directly in their database- and this is totally fine.

**Comment by razor-x** [comment]
> Minor correction: `user_identifier_key` should be optional on backend, because for some backend implementations customers will choose to manage their users without any `user_identifier_keys` by storing the tokens directly in their database- and this is totally fine.

@seveibar Would that change mean every session created without a key would be independent? How would one refresh a session without the key when the token expires?

 If we make that change on the backend, then the default client behavior needs to be decided when `userIdentifierKey` is not passed into the provider. Possible options:

1. Key is not passed to API, no `userIdentifierKey` for the browser.
   - Keep client / server api transparent.
   - Browser will cache the client session token, but there is no key now when the token expires.
2. API returns non-null key and client caches key.
   - This was my original proposal, however it does not match with null keys.
3. Keep current client key generation and cache behavior. Using a null client key must be explicit by passing exactly `userIdentifierKey={null}`
   - Cleanest default behavior IMO.
   - Might be surprising unless API also distinguishes between null and undefined.
