### ISSUE TITLE
DeviceDetail/AccessCodeTable - Update story to load device not hardcode id

### ISSUE THREAD

**Issue by mikewuu** [seamapi/react#150]
Currently in `DeviceDetails.story`, we're hardcoding the `deviceId`. This poses issues, such as if the device was deleted. We should instead use storybook loaders to fetch a list of devices, then just pick an id from there, so we can always be sure that the id is valid.

### Stories to update:

- [ ] DeviceDetails
- [ ] AccessCodeTable

### Original comment

> This is going to be an issue since the device ID will depend on the workspace, fake or real. We need to use loaders https://storybook.js.org/docs/react/writing-stories/loaders to fetch the list of devices and pick one of the IDs. Does not block the PR: can make this an issue.

_Originally posted by @razor-x in https://github.com/seamapi/react/pull/148#discussion_r1194169427_

**Comment by razor-x** [comment]
Done in https://github.com/seamapi/react/pull/151 and https://github.com/seamapi/react/pull/154
