### ISSUE TITLE
`<AccessCodesTable />` - Add issues icon and health bar

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#241]
# Tasks
- [ ] Add access code issues filter
- [ ] Add issues icon to table row

## Designs
<img width="874" alt="Screen Shot 2023-06-27 at 5 14 16 PM" src="https://github.com/seamapi/react/assets/1843707/6b7b4754-ed04-4bf2-b081-0925eed8555a">

[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=258-26284&mode=design&t=3X8X5SvJe6m7Z5df-0)

![Image](https://github.com/seamapi/react/assets/1843707/73816b6b-4e13-456e-957b-0be01f593c28)

## What the data looks like
If an access code has any errors, we should show this red issues icon.

When an access codes's `errors` list is empty, an access code has no errors.

**Comment by xplato** [comment]
Is this listing errors/warnings for access codes? Do they show up at the top?

Any additional context here?

**Comment by xplato** [comment]
@mikewuu are you able to take this on? If not, I can—just let me know!
