### ISSUE TITLE
Devices Table

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#27]
## Designs

We will not be implementing the modal, as Jurny wants to use their own modal. We'll just be focusing on the innards. I want to get y'all's inputs on how we might tie one view to another

![Image](https://user-images.githubusercontent.com/1843707/235368286-ad8a44bf-9a01-4e19-b2da-d2d656f8d597.png)
[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Out-of-the-box-Components?type=design&node-id=291-40595&t=EyoxpYXT25IB2jin-0)

Note, we're going to implement infinite scroll, as opposed to pagination.

## Properties
Publicly available props for the component:

```
interface DevicesTableProps {
    deviceIds?: Array<string>
    onDeviceRowClick?: (deviceId: string) => void
    sortBy: "name" | "createdAt"
}
```
We'll list out all the devices listed in `deviceIds`. If `deviceIds` is undefined, show all devices.

`onDeviceRowClick` will allow a user to customize what they do when a user clicks on a device row.

## Search

Search should look over the devices' `name` and `location` data.

## Default Sort
We'll sort the devices by `name`.

**Comment by seveibar** [comment]
just a note: don't use the prefix `handle*`, use `onDeviceRowClick`

**Comment by seveibar** [comment]
`deviceIds` and `onDeviceRowClick` should be an optional. If device ids is not provided, show all devices. If `onDeviceRowClick` is not provided, show a device view modal on click.

**Comment by dawnho** [comment]
> `deviceIds` and `onDeviceRowClick` should be an optional. If device ids is not provided, show all devices. If `onDeviceRowClick` is not provided, show a device view modal on click.

I don't want to show all devices if it is empty here.

**Comment by dawnho** [comment]
@azat-co feel free to add on the sorting and searching params that you suggested!

**Comment by razor-x** [comment]
@azat-co @mikewuu Might be helpful for the case conversion when using types from seamapi: https://javascript.plainenglish.io/transform-mapped-types-from-snake-to-camelcase-in-typescript-472a2a4843b9
