### ISSUE TITLE
Designs for loading and error states

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#287]
## Supported Devices Table

- Loading state / error states
- Search / filter, no results found

## AccessCodeTable / DeviceTable / (Any)Table:
- Loading state / error states
- No Items returned
- Search / filter, no results found

## AccessCodeDetails & Device Details / (Any)Details:
- Loading state / error states
- 404 Not Found

## AccessCodeForm / (Any)Form
- ~Loading state / error states~ Moved to https://github.com/seamapi/react/issues/402
- 404 Not Found

## Connect Account Button
- Loading state for when clicked
- Error state for when the API did not create a connect webview

**Comment by miken-seam** [comment]
The snack bar works for errors, but not as a loading indicator. I tried a mini floating version but it's too heavy handed to show loading status. I'm thinking a set of messaging methods should work for most situations:
 1) Centered message with spinner for component first load
 2) Floating or inline feedback for loading
 3) Snackbar for error.

There's more to do on this, but wanted to get feedback first.  

Here are two scenarios for...
- loading the component at first
- loading devices
- error when trying to load devices

I think the dark loading floater is too strong, but i think the steps are right. Send feedback and I'll revise.
Watch prototype: https://github.com/seamapi/react/assets/112443289/af91eae0-c7bf-47e7-95d2-d79e4ce4ad49

**Comment by miken-seam** [comment]
@razor-x @dawnho Here's a set of prototypes for 7 of the different cases in the original issue comment. Some are small and some are large.

The same basic little floating feedback widgets work on different sizes and shouldn't interrupt anything in the ux.

The link below goes to an index. Click the link to see the prototype. You can **type R** on your keyboard at any time to return to the index page.

This isn't done but wanted to get feedback before going further. The system seems pretty ok, but i can try it in a few other contexts before building it.

Click here to try the prototypes:
https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=1871%3A14268&mode=design&t=oAQRPDWRn1B2J9J9-1

**Comment by miken-seam** [comment]
Updated figma prototype link...

https://www.figma.com/proto/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?page-id=1871%3A14268&type=design&node-id=1931-38264&viewport=2319%2C211%2C0.45&t=OCrhXwOtO36XlHRG-1&scaling=min-zoom&starting-point-node-id=1931%3A38264&show-proto-sidebar=1&mode=design
