### ISSUE TITLE
Device Details

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#29]
## Designs
![Image](https://user-images.githubusercontent.com/1843707/235367639-e4b80faf-3150-46a1-acbd-8c45ea8f3748.png)
[Link to figma](https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Out-of-the-box-Components?type=design&node-id=322-38129&t=EyoxpYXT25IB2jin-0)

## Properties
Publicly available props for the component:

```
interface DeviceDetailsProps {
    deviceId: string
    onAccessCodesMenuClick?: () -> void
}
```
We'll show the device with the id `device_id`.

There might be different types of devices, i.e. locks, thermostats, noise sensors.

### For battery / power
See the device's `battery_status`, it can be `full` | `good` | `low` | `critical`, please show appropriate icons for different levels
Some devices are wired in, for those, look for a `has_direct_power` attribute on the metadata properties. If set to `true`, show: `powered` with a plug icon

### In the properties/settings panel on the right:
For devices with the capability `lock`, we'll show:
`Lock status: "Locked" | "Unlocked"` with a "Lock" or "Unlock" button

For devices with the capability `access_code`, we'll show:
`Code length: ${number} digits`
Where the lock supports a range of digit lengths, try to show `6 - 10 digits`

For devices with the capability `noise_sensor`, we'll show:
`Noise level: ${number} db`

Thermostats will be coming soon.

## Errors / Warnings
See the `errors` and `warnings` properties on the device.

**Comment by mikewuu** [comment]
@dawnho Similar to https://github.com/seamapi/react/issues/26, I've spun this out into separate issues:

- https://github.com/seamapi/react/issues/112
- https://github.com/seamapi/react/issues/109
- https://github.com/seamapi/react/issues/110
- https://github.com/seamapi/react/issues/111
