### ISSUE TITLE
Unable to bind functions react components from Vue 2.7.14

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#291]

**Comment by razor-x** [comment]
I forked react-to-web-component and implemented an `object` prop type: https://github.com/rxfork/react-to-web-component/pull/2

This should resolve the binding issue.

**Comment by razor-x** [comment]
Testing on this branch: https://github.com/seamapi/seam-components-sample-apps/pull/5/files#diff-53aa8b9c5e3e1a3ef51117278e2a9efbc2e9d6c7a61449f9ef17219bfda52cf7
