### ISSUE TITLE
`DeviceTable` - Include thermostats 

### ISSUE THREAD

**Issue by xplato** [seamapi/react#307]
<img width="475" alt="Screenshot 2023-07-24 at 11 57 41 AM" src="https://github.com/seamapi/react/assets/87919558/2125e524-d861-400c-9367-0d09aad0bfb7">

---

https://www.figma.com/file/WTdzEh4CudGdQFOtuVR3Eh/Thermostat%2FNoise-components?type=design&node-id=830-88326&mode=dev

**Comment by razor-x** [comment]
@xplato Is this complete?

**Comment by xplato** [comment]
They are included in the list but they do not link to the details page just yet. Working on this now.
