### ISSUE TITLE
 Toggle manual override

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#395]

**Comment by xplato** [comment]
It appears this is implemented:

![Image](https://github.com/seamapi/react/assets/87919558/d9c8686f-1a8e-477d-8632-ce509dd7361f)

**Comment by mikewuu** [comment]
@razor-x, @xplato, can I get more context for this one? 

> It appears this is implemented:

From the screenshot, it looks implemented to me too 😛

**Comment by xplato** [comment]
@mikewuu this issue is for the climate setting details component--the one I pictured was the thermostat device details. 

My bad, should have added this info the first time!

**Comment by mikewuu** [comment]
ah gotcha, so different modal, but the needs the same UI?

**Comment by xplato** [comment]
@mikewuu I believe so, yes.

**Comment by mikewuu** [comment]
cool, thanks!
