### ISSUE TITLE
Design for create and update success and error flow

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#402]
- Submit form: what if there is an API error?
  - What does a per-form-field error look like?
  - What does a general creation error look like?
- Submit form: navigate and show message.

**Comment by miken-seam** [comment]
This prototype contains other states. For the form error states, click number 10 on the index page. https://www.figma.com/file/Su3VO6yupz4yxe88fv0Uqa/Seam-Components?type=design&node-id=1931%3A38264&mode=design&t=NFwxZOpe3IXAuMkY-1

<img width="2102" alt="image" src="https://github.com/seamapi/react/assets/112443289/e04b94a3-496a-4bde-9708-840dcde3ba9b">

**Comment by razor-x** [comment]
@miken-seam Anyway to leave the space for the message so things don't jump around?
