### ISSUE TITLE
Show fan mode on UI

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#415]
Waiting on API update to expose this property.

**Comment by xplato** [comment]
I believe this is implemented, both display and mutation.



![Image](https://github.com/seamapi/react/assets/87919558/d6f7c61b-bc97-41df-817d-53ad7e4792ec)
![Image](https://github.com/seamapi/react/assets/87919558/9b1fa699-7013-4cd7-b1f3-45cfa67e5056)
