### ISSUE TITLE
Thermostat types missing default_climate_setting

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#417]
See https://github.com/seamapi/react/blob/65a2d8540664ca9f04962a1843b54c60eeba9465/src/lib/seam/components/DeviceDetails/ThermostatDeviceDetails.tsx#L103

This was added in a new JS sdk version, but there is a new issues with the types that must be fixed now before this may be used here.

**Comment by Andrewjeska** [comment]
I think we're good now right @razor-x ?
