### ISSUE TITLE
Empty results message not centered

### ISSUE THREAD

**Issue by miken-seam** [seamapi/react#423]
<img width="1135" alt="image" src="https://github.com/seamapi/react/assets/112443289/6c00e59e-6f6d-41a9-85ab-fabbab3472ac">

**Issue:**
- Message shows left-aligned in module instead of centered. This is seen when getting a null search results in safari at docs.seam.co/latest/seam-components/react-components/supported-devices-table
- The message centers properly on react.seam.co but not on docs.seam.co

**Solution:**
- Make sure the message is horizontally centered in different contexts

cc @sybohy

**Comment by mikewuu** [comment]
Not actually seeing the table being rendered at [https://docs.seam.co/latest/seam-components/react-components/supported-devices-table](https://docs.seam.co/latest/seam-components/react-components/supported-devices-table)

@razor-x are the docs broken here?



![Image](https://github.com/seamapi/react/assets/11449462/a464b503-3e65-46e6-9ac4-d3fee849f071)

**Comment by mikewuu** [comment]
@miken-seam, not able to reproduce / already fixed. Closing issue for now.
