### ISSUE TITLE
Filter dropdown opens in wrong place

### ISSUE THREAD

**Issue by miken-seam** [seamapi/react#424]
<img width="1563" alt="image" src="https://github.com/seamapi/react/assets/112443289/7c72308b-da11-4ed0-9959-a459e3cfacd6">

In the supported devices component the dropdown opens far away from the filter button that triggers it.

**Issues:**
- On the react.seam.co preview version, the dropdown menu pops up in the wrong place
- Clicking on the “All” button appears to do nothing. There’s a hover and a click state but nothing happens on click. (on react.seam.co)

**Solution:**
- Check behavior in multiple contexts and browsers

cc @sybohy

**Comment by razor-x** [comment]
Is this the same issue? I think your description is more detailed.

**Comment by miken-seam** [comment]
@razor-x looks the same to me
