### ISSUE TITLE
Ensure full control over back button and close button

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#489]
User reports not able to hide close and back buttons. Need to either reproduce this or close as confirmed working.

**Comment by chamokk** [comment]
Hey! Could you add more details about this issue?

**Comment by razor-x** [comment]
Sure. A user of this library expressed a concern that the `onBack` and `onClose` props may not be used or exposed consistently. This issue was opened to remind us to look into that concern.

The `onBack` prop is called anytime the "back" button is clicked inside a child view. Looking for `onClose`, I see this prop is not part of the API, so that may just be a misunderstanding by the user.

Actually, I am going to close this issue, since the original reporter later said they could not confirm it themselves. If there is a known case where `onBack` is missing or not working, I am happy to reopen. Thanks!
