### ISSUE TITLE
Stale data after updating an access code

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#491]
Chancing the name of an access code works, but the ui does not refresh with the new name. Maybe we can connect some update logic into this flow: https://github.com/seamapi/react/issues/479

**Comment by mikewuu** [comment]
@razor-x this seems to be working as expected. We're invalidating the queries, which should fetch the latest (updated) data?

https://github.com/seamapi/react/assets/11449462/8876da97-d7f5-4401-8ae4-c0f52f773bb0

**Comment by razor-x** [comment]
Can you try it on the example app? The Storybook uses the fake which updates instantly. We should probably update the fake to have a delay.
