### ISSUE TITLE
Show annotations on supported manufactures

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#565]
Some manufactures have additional considerations that should be communicated to users of the supported device table. For example, Nuki locks require a separate subscription to Nuki for Seam to use all features.

The internal devicedb API will be updated to provide this data. The SupportedDeivceTable will then display this notice on the manufacturer. 

Blockers for updating the component:

- [x] Update devicedb to return the notice.
- [x] Update https://github.com/seamapi/fake-devicedb API to match.
- [x] Update devicedb seed here to pull the notice into the seed data.
- [x] Design mockup for the notice.

**Comment by miken-seam** [comment]
Here's the figma link for the banner design.
https://www.figma.com/file/6nCfNVHmYQ7wxhnFOpFBm6/Supported-devices?type=design&node-id=487%3A31328&mode=dev

cc @dawnho @seveibar  since @razor-x is out

https://github.com/seamapi/react/assets/112443289/0669deaa-94ff-46dd-bd6c-7b6f0af5b339
