### ISSUE TITLE
Hide manual code input and remove edit/delete buttons for offline access codes

### ISSUE THREAD

**Issue by aramhostaway** [seamapi/react#591]
- remove code input field in access code component when device does not support manually set codes or update codes. Like offline devices.
- remove (disable) edit and delete button for offline access codes

**Comment by justsayknarf** [comment]
Product spec: https://www.notion.so/seamco/Seam-Component-Disable-edit-code-for-offline-access-codes-17819454737d4aa5ad329e22c8b25aed?pvs=4
