### ISSUE TITLE
Add `disableConnectedAccountInformation` prop to common props

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#610]
For End users who don't own the device, we don't want to show them the account email address, and device ID.

To-dos:
- Rename "Device Details" section to "Device Info"
- Add `disableConnectedAccountInformation` to `<DeviceDetails />` and `<DeviceTable />` components

This section is what we want to hide:
![Screen Shot 2024-03-15 at 10 35 45 AM](https://github.com/seamapi/react/assets/1843707/6a3a8d09-cbff-477e-a70a-d8f4e800b09e)

**Comment by dawnho** [comment]
Some ideas, we can rename this section to "Device information", the property could be renamed to `disableDeviceInformation`.

Thoughts? @razor-x @xplato

**Comment by razor-x** [comment]
Is the manufacturer useful? We already have  `disableResourceIds` which covers one of the fields. What if we add `disableConnectedAccountInformation`?

**Comment by dawnho** [comment]
For the resident, probably not, I don't think the need to know the manufacturer. They're just interested in the thermostat controls and seeing the current temperature / settings

**Comment by dawnho** [comment]
@razor-x To hide that whole section, would they just need to set both `disableConnectedAccountInformation` and `disableResourceIds` to `true?

**Comment by razor-x** [comment]
Ok, I've updated the title, we can add `disableConnectedAccountPii`, but I don't think it makes sense for this to control the manufacturer.

To hide both the email / id, they would set `disableResourceIds` and `disableConnectedAccountPii`.

I still think hiding this entire section this is the same case as https://github.com/seamapi/react/pull/607 and is out of scope of the prop API. The API focuses on controlling functionality and behaviors, not tweaking UI at the component level from the global scope.

In my opinion, we should not add a new prop. Even `disableDeviceInfo` is  and instead:

1. Re-title this section to `Device Info`.
2. Add a CSS class `seam-device-info` to this section.
3. The user can set a CSS hidden property for `seam-device-info`.

**Comment by dawnho** [comment]
@razor-x I kind of prefer `disableConnectedAccountInformation` to `disableConnectedAccountPii`. Pii is an acronym, and not all the information being hidden is personally identifying.

**Comment by razor-x** [comment]
Looking at this with fresh eyes, this row only exists on `ThermostatDeviceDetails`. We should either remove it entierly from the component, or add it consistently to all device detail components and add the prop to disable it.

```
              <DetailRow
                label={t.linkedAccount}
                sublabel={
                  connectedAccount?.user_identifier?.email ??
                  device.connected_account_id
                }
              />
```

**Comment by dawnho** [comment]
I think this can be valuable for all device types.
This section shows the device id and connected account info
