### ISSUE TITLE
Reduce size of images in Seam Components

### ISSUE THREAD

**Issue by justsayknarf** [seamapi/react#616]
## Context
Customers may embed the Supported Devices Seam Component in their app as a way to encourage their users to manage devices in the platform. Because of these large filesize, it's taking up to 10s to load the page, which can affect the platform's user feature adoption.

[] need sized source images (need to export from figma at different sizes)
[] need devicedb to return alt image sizes

Slack context: [LINK](https://hello-seam.slack.com/archives/C051ETBPRTQ/p1709930872682989)

**Comment by razor-x** [comment]
Image urls returned by the Seam API are now optimized!
