### ISSUE TITLE
Fix compatibility with new thermostat types

### ISSUE THREAD

**Issue by razor-x** [seamapi/react#658]
Basic thermostat control should still work, but anything related to climate setting schedules will need to be removed and brought back later as climate presets plus thermostat schedules.

The most important thing is to fix any type errors with the latest types, as this will block users from updating.

**Comment by razor-x** [comment]
@mikewuu I merged the last PR into the `beta` branch. We can keep working off of `beta` until we finish making breaking changes.

1. I found `is_climate_setting_schedule_active`. Can you search for any other instances of `climate_setting_schedule` or similar?
2. We should remove climate_setting_schedules from fake-seam-connect as well.
3. Let's remove `manual_override_allowed` and `is_temporary_manual_override_active` and related stuff. Those API are also changing.

**Comment by mikewuu** [comment]
@razor-x removed a couple stragglers in https://github.com/seamapi/react/pull/661
