### ISSUE TITLE
Remove localStorage of client session and user identifier keys

### ISSUE THREAD

**Issue by seveibar** [seamapi/react#78]
Client sessions should not be cached. Their access can change, and they can only be cached relative to a particular user identifier key.

User identifier keys should also not be cached, the only time a user identifier key should be stored in local storage is if it's a fingerprint, and in that case it is not really a user identifier key cache but a fingerprint cache that is used as a user identifier key if one is not provided

**Comment by razor-x** [comment]
Should we change the provider API to require `userSessionKey`?

**Comment by razor-x** [comment]
Done in https://github.com/seamapi/react/pull/80
