### ISSUE TITLE
`lib` should be `dist`

### ISSUE THREAD

**Issue by seveibar** [seamapi/react#79]
It's not clear that `lib` is an output directory, and it's redundant within the project's `src/lib`

**Comment by seveibar** [comment]
there's also something where you can't import `ts` files or directories as you can in a normal typescript project

**Comment by razor-x** [comment]
We have an open discussion for bundling requirements and concerns: https://github.com/seamapi/react/discussions/36 Can we close this as a duplicate?

Note that my thought was to reserve `dist` for bundled output and the root of the package mimics `src` and `.ts` complies 1to1 to `.js.`

> there's also something where you can't import ts files or directories as you can in a normal typescript project
Not sure I understand this. Do you have an example of this issue?
