### ISSUE TITLE
Wrap modal contents in `.seam-components` class

### ISSUE THREAD

**Issue by mikewuu** [seamapi/react#85]
Will this make integration difficult for our consumers? Do we need to document this or can we find a solution that will wrap the model in the right class?

_Originally posted by @razor-x in https://github.com/seamapi/react/pull/47#discussion_r1184397047_
            
To avoid consumers from having to wrap modals in `.seam-components`, we'll automatically wrap all components in this class again.

**Comment by razor-x** [comment]
How about this solution?

- Remove class from provider.
- Add to all top level components.
- Remove from story dialog components.

**Comment by razor-x** [comment]
Documented here https://github.com/seamapi/react/pull/477
