### ISSUE TITLE
Add navigation buttons to handle nested component state

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#92]
For each component, I want to add the following props:
- `enableBack: bool | (componentName: string, componentProps: object) => void`
  - If set to `true`, we show the back button, if a handler is set, we can call the function whenever the back button is clicked.
- `enableClose: bool | () => void`
  - If set to `true`, we show the close button, if a handler is set, we can call the function whenever the close button is clicked.
- `disableRedirect: bool`
  - will the component redirect to another page when a button is pressed?
  - default to `false`

This will apply to the following components:
- DeviceDetails
- DevicesTable
- AccessCodeDetails
- AccessCodesTable

**Comment by razor-x** [comment]
What if we only show the back and close buttons if they provide onBack/onClose handlers?

**Comment by razor-x** [comment]
Actually it's a quick follow-up if the redirection behavior is the default then the prop we add should be the override behavior. So one of these: `disableRedirect` / `willNotRedirect`

**Comment by seveibar** [comment]
👍 `disableRedirect` / `noRedirect` are both good imo

**Comment by seveibar** [comment]
Also agree with @razor-x that we should remove `isBackButtonShown` and `isCloseButtonShown`, they are implied by `onClose` `onBack`

**Comment by dawnho** [comment]
If we're going with `disableRedirect`, we might want to rename some of the other props like `canEdit` and `canDelete` to `enableEdit` and `enableDelete`. Seems strange to use different terminology for different props

**Comment by dawnho** [comment]
@razor-x @seveibar, did some edits. have a look again.

**Comment by mikewuu** [comment]
> disableRedirect: bool
will the component redirect to another page when a button is pressed?

@dawnho can you provide examples of buttons for these? 

My gut feeling is that `disableRedirect` may be too broad. What if there are multiple buttons / actions? What if the user actually just wants to trigger some other side-effect, but still redirect?

Couple alternatives:

**1. specific `onClick*`  handlers.**

Users can supply a custom `onClick*` handler which receives the redirect function.

```tsx
<AcessCodeTable onClickAccessCode={ ({accessCode, viewCode}) => {
    console.log(accessCode) // some side effect
    viewCode() // show access code detail
} }/>
```

**2. Custom component overrides**

```tsx
<AcessCodeTable accessCodeRow={ ({accessCode, viewCode}) => (   
    <CustomRow onClick={ () => console.log('do nothing!') }/>
) }/>
```

**Comment by dawnho** [comment]
> @dawnho can you provide examples of buttons for these?

Totally!

- On the `<DeviceList />`, when you click on the device row.
- On the `<DeviceDetails />`, when you click on the '{n} Access Codes' button
- On the `<AccessCodeList />, when you click on an access code row.
- On the `<AccessCodeDetails />`, when you click on 'Device details'

**Comment by razor-x** [comment]
I agree with @mikewuu. Better to define props that do not assume a specific behavior, just add `on*` event hooks like `onClickAccessCode`. Maybe better to do `onAccessCodeClick` so related props are naturally grouped, e.g., `onAccessCodeClick` with `onAccessCodeHover` etc.

I disagree with the polymorphic `enableBack`, etc. It's not clear what that means without the handler. Actually I think there may be a larger implicit assumption we should resolve. We have modal and non-modal cases for the components, but really the modal API should be a container that hosts the components, not integrated into them. Currently the model close and back buttons are not part of the lib, they are wrappers in the story, which means they would be implemented by the consumer. If we want to provide a modal UI in the lib, then `onBack`, etc., would not be props of `DeviceDetails`, etc., but props of the modal wrapper component.

@mikewuu It would be helpful if you can drop an example here of how you ideal API might look when the components are used inside vs. outside the modal.

**Comment by mikewuu** [comment]
Thanks! Given the above examples, I'd suggesting using option **1. specific onClick* handlers.**.

**Comment by mikewuu** [comment]
> Maybe better to do onAccessCodeClick so related props are naturally grouped, e.g., onAccessCodeClick with onAccessCodeHover etc.

This is a good idea! As a consumer I'd appreciate the auto-complete this provides.

**Comment by mikewuu** [comment]
> Currently the model close and back buttons are not part of the lib, they are wrappers in the story, which means they would be implemented by the consumer.

I'm thinking of having the back button be a part of the content, that is, it'll show whether it is being rendered in a modal, or on a page. 

If a user wants to customize their own back buttons, they can specify custom components.

```tsx
function App() {
  return <DeviceDetail BackButton={DeviceBackButton} />
}
```

**DeviceBackButton**

```tsx
function DeviceBackButton() {
  return <button>close device/>
}
```

They can also override child components, or entire sections:

```tsx
function App() {
  return <DeviceDetail AccessCodeTable={CustomAccessCodeTable} />
}
```

**CustomAccessCodeTable**

```tsx
function CustomAccessCodeTable(props: AccessCodeTableProps) { 
  return (<div>my table...</div>)
}
```

**Comment by dawnho** [comment]
> I'm thinking of having the back button be a part of the content

These are great ideas!

Reminds me of how MUI did their dialogs. See [this example](https://mui.com/material-ui/react-dialog/#customization) for instance.

I do want to keep things as easy as possible for our users. One piece of logic that might be time-consuming to implement is the navigation history of the modal.

Is there a way to provide this modularity (allowing a user to add a back button as part of content), but also take care of this complex logic?

**Comment by razor-x** [comment]
The component override system is a neat idea, but I am unsure if we should try to implement that at the start. I think it can always be added later to give consumers more control.

We still need a direct answer to this question: Will this lib provide a modal implementation?

It sounds like components that can navigate to other components will
effectively have a router built into the component. I'm concerned this will make the individual components too complex.

We can contain this complexity by implementing the `on*` props first, and then using those to build the navigation layer. For example, `DeviceList

```ts
function DeviceList({ onDeviceClick }) {
  // ...
}

function DeviceListWithRouter({ onClose }) {
  // implement routing state logic here along with handleDeviceClick to set deviceId
  if (deviceId)
    return (
      <>
        <CloseButton onClose={onClose} />
        <BackButton />
        <DeviceDetails deviceId={deviceId} />
      </>
    );
  return (
    <>
      <CloseButton onClose={onClose} />
      <DeviceList onDeviceClick={handleDeviceClick} />
    </>
  );
}

```

**Comment by dawnho** [comment]
Our first set of components will be designed specifically for Jurny.

Based on the videos, Jurny has a modal, but none of the innards implemented.

This is why I wanted to prioritize the navigation functionality.

Here's a screenshot of their modal with the webview:
![Screen Shot 2023-05-07 at 2 00 20 PM](https://user-images.githubusercontent.com/1843707/236702358-f7478445-6296-431e-85dc-22230d397d36.png)

**Comment by mikewuu** [comment]
> The component override system is a neat idea, but I am unsure if we should try to implement that at the start. I think it can always be added later to give consumers more control.

Yep, agreed.


> . I'm concerned this will make the individual components too complex.

At an individual component level, it looks ok for now:

> On the <DeviceList />, when you click on the device row.
On the <DeviceDetails />, when you click on the '{n} Access Codes' button
On the <AccessCodeList />, when you click on an access code row.
On the <AccessCodeDetails />, when you click on 'Device details'

Each component only conditionally renders at most 1 other component. 

IMO we can build the routing into the component for now, and just make it an optional prop.

```tsx
type Props = {
  onDeviceClick: (device: Device) => void,
  onBack?: () => void
}

function DeviceList({ onDeviceClick, onBack }: Props) {  if (deviceId)
    return (
        <DeviceDetails deviceId={deviceId} onBack={unselectDevice} />
    );
    
  return (
    <>
      {onBack && <BackButton onBack={handleBack} />}
      <DeviceList onDeviceClick={handleDeviceClick} />
    </>
  );
}
```

- `<CloseButton/>` is a modal implementation, and I don't think we need to include it.

**Comment by dawnho** [comment]
Can we also add the close button? I don't think they have one yet.

**Comment by mikewuu** [comment]
Sure, we can definitely include a default one in the lib.
