### ISSUE TITLE
AccessCodes Table - Fix horizontal sizing

### ISSUE THREAD

**Issue by dawnho** [seamapi/react#93]
Horizontal scroll bar showing when access code table is inside a modal

<img width="779" alt="image" src="https://user-images.githubusercontent.com/112443289/236526172-26760d77-eb00-455a-bf63-4fb937adb896.png">

Also there's no more (overflow) button at the end of each row, but I'm not sure if that's meant to be there yet.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/112443289/236527038-bf1e3d0a-c868-4cee-ae1f-e9a986edf58e.png">

**Comment by dawnho** [comment]
Copied from this: https://github.com/seamapi/space-frontend/issues/793

**Comment by mikewuu** [comment]
@dawnho I've split the 'missing overflow (menu)' button into separate issues:


- https://github.com/seamapi/react/issues/107
- https://github.com/seamapi/react/issues/30 (Added **other requirements** in description)

**Comment by mikewuu** [comment]
Removed 'Missing overflow' from title as that'll be handled in separate issues above.
